apiVersion: v2
appVersion: v2.3.4
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argocd-security
version: 4.8.2
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: turkel kadirzade
dependencies:
  - name: argocd-apps
    version: 0.0.9
    repository: https://argoproj.github.io/argo-helm
