apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
automountServiceAccountToken: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin-helm
      generate:
        command: ["sh", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" -n "$ARGOCD_APP_NAMESPACE" . | argocd-vault-plugin generate -']

---

apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  repo:

    serviceaccount: "argocd-repo-server"

    # 1. Define an emptyDir volume which will hold the custom binaries
    volumes:
    - name: custom-tools
      emptyDir: {}
    # 2. Use an init container to download/copy custom binaries into the emptyDir
    initContainers:
    - name: download-tools
      image: alpine:3.8
      command: [sh, -c]

      # Don't forget to update this to whatever the stable release version is
      # Note the lack of the `v` prefix unlike the git tag
      env:
        - name: AVP_VERSION
          value: "1.7.0"
      args:
        - >-
          wget -O argocd-vault-plugin
          https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

    # Not strictly necessary, but required for passing AVP configuration from a secret and for using Kubernetes auth to Hashicorp Vault
    automountServiceAccountToken: true
    
    # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
    volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/argocd-vault-plugin
      subPath: argocd-vault-plugin

    # Note: AVP config (for the secret manager, etc) can be passed in several ways. This is just one example
    # https://argocd-vault-plugin.readthedocs.io/en/stable/config/
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials