apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
automountServiceAccountToken: true

---

apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  image: kadirzade/argocd:v2.3.4
  repo: 
    serviceaccount: "argocd-repo-server"