apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-server-secret
  annotations:
    kubernetes.io/service-account.name: argocd-repo-server
type: kubernetes.io/service-account-token

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
automountServiceAccountToken: true
secrets:
  - name: argocd-repo-server-secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME --include-crds . |
            argocd-vault-plugin generate -
      lockRepo: false

---

apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  repo: 
    serviceaccount: "argocd-repo-server"
    mountsatoken: true
    volumes:
      - configMap:
          name: cmp-plugin
        name: cmp-plugin
      - name: custom-tools
        emptyDir: {}

    initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: 1.14.0
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    sidecarContainers:
    - name: avp
      command: [/var/run/argocd/argocd-cmp-server]
      # image: registry.access.redhat.com/ubi8
      image: alpine/helm:3.11.1
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      env:   
        - name: AVP_K8S_MOUNT_PATH
          value: auth/sahab2/dev/security-operator-dev      
        - name: AVP_K8S_ROLE
          value: security-operator-dev  
        - name: VAULT_ADDR
          value: http://host.minikube.internal:8200 
        - name: AVP_TYPE
          value: vault  
        - name: AVP_AUTH_TYPE
          value: k8s  
        - name: VAULT_SKIP_VERIFY
          value: "1"  
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp

        # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp-helm.yaml
          name: cmp-plugin

        # Important: Mount tools into $PATH
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin